#!/bin/bash --verbose
# Copyright 2012-2013 David Shields
#
# This program does a sanity test on the 64-bit version of spitbol, to  verify that spitbol is able to compile itself.
# This is done by building the system three times, and comparing the generated assembly (.s) files. 
# Normally, all three assembly files wil be equal. However, if a new optimization is
# being introduced, the first two may differ, but the second and third should always agree.
#
rm tbol.*
sys=spitbol_unix_64
echo "start  sanity test unix gas 64"
cp	./bin/$sys testbol
make clean>/dev/null
make base=./testbol ws=64 gas
mv sbl.lex tbol.lex.0
mv sbl.s tbol.s.0
mv spitbol tbol
make base=./testbol ws=64 gas
mv sbl.lex tbol.lex.1
mv sbl.s tbol.s.1
mv spitbol tbol
make base=./testbol ws=64 gas
mv sbl.lex tbol.lex.2
mv sbl.s tbol.s.2
rm ./testbol
echo "comparing generated .s files"
diff tbol.s.1 tbol.s.2
echo "end sanity test"
