#!/bin/bash --verbose
rm tbol.*
echo "start sanity test"
cp	basebol	tbol
make clean>/dev/null
make BASEBOL=./tbol
mv s.lex tbol.lex.0
mv s.s tbol.s.0
cp spitbol tbol
make BASEBOL=./tbol
mv s.lex tbol.lex.1
mv s.s tbol.s.1
cp spitbol tbol
make BASEBOL=./tbol
mv s.lex tbol.lex.2
mv s.s tbol.s.2
echo "comparing generated .s files"
diff tbol.s.1 tbol.s.2
cp savebol tbol
# test for compile END in lower or upper case
./spitbol ./test/e.spt
./spitbol ./test/E.spt
echo "end sanity test"
