#!/bin/bash --verbose
rm chk.*
echo "start bootstrap test"
git checkout bootbol
cp bootbol savebol
make clean>/dev/null
make
mv s.lex chk.lex.0
mv s.s chk.s.0
cp spitbol bootbol
make
mv s.lex chk.lex.1
mv s.s chk.s.1
cp spitbol bootbol
make
mv s.lex chk.lex.2
mv s.s chk.s.2
echo "comparing generated .s files"
diff chk.s.1 chk.s.2
cp savebol bootbol
echo "end bootstrap test"
