#!/bin/bash --verbose
rm chk.*
echo "start bootstrap test"
git checkout bootbol
cp bootbol savebol
make clean>/dev/null
make -f tcc-makefile
mv s.lex chk.lex.0
mv s.s chk.s.0
cp spitbol bootbol
make -f tcc-makefile
mv s.lex chk.lex.1
mv s.s chk.s.1
cp spitbol bootbol
make -f tcc-makefile
mv s.lex chk.lex.2
mv s.s chk.s.2
echo "comparing generated .s files"
diff chk.s.1 chk.s.2
cp savebol bootbol
# test for compile END in lower or upper case
./spitbol ./test/e.spt
./spitbol ./test/E.spt
echo "end bootstrap test"
