#!/bin/bash --verbose
# Copyright 2012-2013 David Shields
#
# This program does a sanity test on spitbol to  verify that spitbol is able to compile itself.
# This is done by building the system three times, and comparing the generated assembly (.s)
# filesbl. Normally, all three assembly files wil be equal. However, if a new optimization is
# being introduced, the first two may differ, but the second and third should always agree.
#
rm tbol.*
echo "start 64-bit sanity test"
make clean>/dev/null
cp	./bin/sbl_unix_64 tbol
ls -l tbol
make 	basebol=./tbol unix_64_nasm
mv bld/sbl.lex tbol.lex.0
mv bld/sbl.s tbol.s.0
cp sbl tbol
ls -l tbol
make 	basebol=./tbol  unix_64_nasm
mv bld/sbl.lex tbol.lex.1
mv bld/sbl.s tbol.s.1
cp sbl tbol
make 	basebol=./tbol  unix_64_nasm
mv bld/sbl.lex tbol.lex.2
mv bld/sbl.s tbol.s.2
echo "comparing generated .s files"
diff tbol.s.1 tbol.s.2
echo "end sanity test"
