	%define CP	RBP
	%define	XL	RSI
	%define	XT	RSI
	%define	XR	RDI
	%define	WA	RCX
	%define WA_L	CL
	%define	WB	RBX
	%define WB_L    BL
	%define	WC	RDX
	%define WC_L    DL
	%define	XS	RSP
	%define	W0	RAX
	%define	W0_L	AL
	%define	IA	RDX
	%define M_WORD  QWORD
	%define D_WORD	DQ
